version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=nodeuser
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    command: node index.js

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
